[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "papers-dl"
authors = [
  { name="Ben Muthalaly", email="benmuthalaly@gmail.com" },
]
description = "A command line application for downloading scientific papers"
readme = "README.md"
requires-python = ">=3.8"
dynamic=["version"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp==3.10.11",
  "bs4==0.0.2",
  "loguru==0.7.3",
  "pdf2doi==1.7",
]

[project.scripts]
papers-dl = "papers_dl:main"

[project.urls]
Homepage = "https://github.com/benmuth/papers-dl"
Issues = "https://github.com/benmuth/papers-dl/issues"

[tool.setuptools.dynamic]
version = {attr = "version.__version__"}
